# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'antibutter/frontend'
        command: 'build'
        Dockerfile: '**/Dockerfile'
- stage: Push
  displayName: Push to Dockerhub
  jobs:
    - job: Push
      displayName: pushing
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Dockerhub'
          repository: 'antibutter/frontend'
          command: 'push'
        
            

