# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'antibutter/frontend:$(Build.BuildId)'

stages:

- stage: Lint
  displayName: Lint
  pool:
    vmimage: "ubuntu-latest"
  jobs:
  - job: Linting
    displayName: Linting
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: "Install Nodejs"
    - script: npm install
      displayName: npm install
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run lint'
    

- stage: Build
  displayName: Build image
  jobs:
  - job: build
    displayName: build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'antibutter/frontend'
        command: 'build'
        Dockerfile: 'dockerfile'
        buildContext: 
- stage: Publish
  displayName: Build image
  jobs:
  - job: push
    displayName: push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'antibutter/frontend'
        command: 'buildAndPush'
        Dockerfile: 'dockerfile'
        buildContext: 


      
